# -*- coding: utf-8 -*-
"""
Created on Wed Jul 26 11:50:52 2023

@author: Nicolas Minesi
"""

version: 0.1

build:
  # os: "ubuntu-20.04"
  tools:
    python: "3.8"

  python:
  # Install our python package before building the docs
  install:
    - method:
        # - conda
        - pip
      path: .
# conda:
#     - numpy
pip:
    - radis

sphinx:
  fail_on_warning: true
formats:
    - pdf
    - epub

